### ISSUE TITLE
这个工具写的非常好，我准备使用，但是有个疑虑。

### ISSUE THREAD

**Issue by bbbbbbbbbbbbba** [vicanso/proxy-pool#1]
我能不能直接用你这个服务提供的接口： https://proxy.aslant.site/

我怕服务不稳定，造成功能不可用，最最好的是你能提供一个sdk包出来。 

我没看你的实现，但是我大概猜测出来了，是从其他网站上抓取可用的免费代理，然后你做可用性检查，将可用的返回。

**Comment by vicanso** [comment]
你可以自己基于Dockerfile来构建镜像，或者直接使用我构建好的镜像`vicanso/proxypool`，启动方式如下：

```
docker run -d \
  --restart=always \
  -p 4000:4000 \
  --name=proxypool \
  vicanso/proxypool
```
